// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RawDataShared;

#nullable disable

namespace RawData.Infrastructure.Migrations
{
    [DbContext(typeof(RawDataContext))]
    [Migration("20231003141023_InsertBusinessUnitData")]
    partial class InsertBusinessUnitData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("RawDataShared.BusinessUnit", b =>
                {
                    b.Property<int>("BusinessUnitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BusinessUnitID");

                    b.ToTable("BusinessUnit");
                });

            modelBuilder.Entity("RawDataShared.Instrument", b =>
                {
                    b.Property<int>("InstrumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("InstrumentID");

                    b.ToTable("Instrument");
                });

            modelBuilder.Entity("RawDataShared.ProfitCentre", b =>
                {
                    b.Property<int>("ProfitCentreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProfitCentreID");

                    b.ToTable("ProfitCentre");
                });

            modelBuilder.Entity("RawDataShared.Trade", b =>
                {
                    b.Property<int>("TradeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusinessUnitID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InstrumentID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProfitCentreID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ReportingAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("TradeID");

                    b.HasIndex("BusinessUnitID");

                    b.HasIndex("InstrumentID");

                    b.HasIndex("ProfitCentreID");

                    b.ToTable("Trade");
                });

            modelBuilder.Entity("RawDataShared.Trade", b =>
                {
                    b.HasOne("RawDataShared.BusinessUnit", "BusinessUnit")
                        .WithMany()
                        .HasForeignKey("BusinessUnitID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RawDataShared.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RawDataShared.ProfitCentre", "ProfitCentre")
                        .WithMany()
                        .HasForeignKey("ProfitCentreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessUnit");

                    b.Navigation("Instrument");

                    b.Navigation("ProfitCentre");
                });
#pragma warning restore 612, 618
        }
    }
}
